export type ModuleGroup = {
  title: string
  modules: string[]
}

export const courseModuleGroups: Record<string, ModuleGroup[]> = {
  ahtm: [
    {
      title: 'Language & Communication',
      modules: [
        'Language Enhancement',
        'Accent Neutralization',
        'Introduction to Grammar',
        'GD & Debate Sessions',
        'Audio Video Comprehension',
        'CV Preparation',
      ],
    },
    {
      title: 'Personality & Soft Skills',
      modules: [
        'Confidence Building',
        'Body Language',
        'Emotional Intelligence',
        'Workplace & Corporate Etiquette',
        'Interview Handling',
      ],
    },
    {
      title: 'Grooming & Presentation',
      modules: [
        'Skin Care',
        'Hair Care',
        'Art of Makeup',
        'Formal Look',
        'Casual Look',
        'Elegant Dressing',
        'Selection of Outfit',
      ],
    },
    {
      title: 'Aviation & Airport Operations',
      modules: [
        'History of Aviation',
        'Types of Aircraft',
        'Aircraft Exterior and Functions',
        'Theory of Flight',
        'Aviation Terminology & Abbreviation',
        'Map Reading Skills',
        'Aviation Authorities & Role of State and Center',
        'Airline',
        'Aircraft Types',
        'In-flight Announcements – English & Hindi',
        'Emergencies on Board',
        'Safety Equipment',
      ],
    },
    {
      title: 'Travel, Ticketing & Tourism',
      modules: [
        'Introduction to Galileo Reservation System & Features',
        'Encoding & Decoding of Cities, Countries',
        'Important Keys & Symbols',
        'Types of Travel & Difference Between Them',
        'Time Zones',
        'Domestic Ticketing and Routings',
        'International Ticketing and Routings',
        'Basic Knowledge of Passport & Visa Structures for Selected Countries',
        'Itinerary Building Techniques',
        'International Itineraries',
        'Domestic Itineraries',
      ],
    },
    {
      title: 'Hospitality & Hotel Operations',
      modules: ['Classification of Hotels'],
    },
  ],
  attm: [
    {
      title: 'Language & Communication',
      modules: [
        'Language Enhancement',
        'Accent Neutralization',
        'Introduction to Grammar',
        'Advanced Grammar',
        'Role-plays Extempore',
      ],
    },
    {
      title: 'Personality & Soft Skills',
      modules: ['Emotional Intelligence'],
    },
    {
      title: 'Grooming & Presentation',
      modules: [
        'The Grooming Process',
        'Skin Care',
        'Hair Care',
        'Art of Makeup',
        'Formal Look',
        'Casual Look',
        'Elegant Dressing',
        'Selection of Outfit',
      ],
    },
    {
      title: 'Aviation & Airport Operations',
      modules: [
        'History of Aviation',
        'Types of Aircraft',
        'Aircraft Exterior and Functions',
        'Theory of Flight',
        'Aviation Terminology & Abbreviation',
        'Map Reading Skills',
        'In-flight Announcements – English & Hindi',
        'Emergencies on Board',
        'Safety Equipment',
        'National Aviation Authorities & Role of State and Center',
        'Airport Access Control: BCAS/Security CISF & Others (Airline Security)',
        'Airport Security',
        'Airport Runway/Taxiway/Maintenance Tarmac/Ramp Area',
        'Airport Infrastructure: City side/Land side/Air side',
        'Airport Monitoring/Surveillance',
        'Airport Administration',
        'Airport Finance',
        'Airport Support System: Fire/Ambulance/Doctors/Water Reservoir',
        'Airport Cargo Security: Incoming/Outgoing Airport Cargo (DGR)',
        "Airport ULD's Equipments",
        'Ground Support Limits',
        'Airport Manager',
        'Airport Threats / Bird Hits / Incident / Accidents',
      ],
    },
    {
      title: 'Travel, Ticketing & Tourism',
      modules: [
        'Introduction to Galileo Reservation System & Features',
        'Types of Travels and Differences among all',
        'International Ticket & Routing',
        'Fares & Ticketing',
        'Passenger Handling',
        'Time Zones',
        'Domestic Ticket & Routing',
        'Basics of Passport & Visa',
        'Domestic Itinerary Building',
        'Encoding & Decoding Cities and Countries',
        'International Itinerary Building',
      ],
    },
  ],
  cchm: [
    {
      title: 'Language & Communication',
      modules: [
        'Language Enhancement',
        'Accent Neutralization',
        'Introduction to Grammar',
        'Advanced Grammar',
        'Role-plays',
        'Extempore',
      ],
    },
    {
      title: 'Personality & Soft Skills',
      modules: ['Emotional Intelligence'],
    },
    {
      title: 'Grooming & Presentation',
      modules: [
        'The Grooming Process',
        'Skin Care',
        'Hair Care',
        'Art of Makeup',
        'Formal Look',
        'Casual Look',
        'Elegant Dressing',
      ],
    },
    {
      title: 'Aviation & Airport Operations',
      modules: [
        'Aviation',
        'Types of Aircraft',
        'Aircraft Exterior and Functions',
        'In-flight Announcements – English & Hindi',
        'Emergencies on Board',
        'Safety Equipment',
        'Brace Positions',
        'Fire and Depressurization',
        'Airline Codes',
      ],
    },
    {
      title: 'Hospitality & Hotel Operations',
      modules: [
        'Introduction to Hospitality Industry',
        'Front Office Introduction',
        'Classification of Hotels',
        'Types of Management',
        'Front Office Procedures for Emergency',
        'Reservation',
        'Tax Structure',
        'Group Arrivals and Departures',
        'Over Booking',
        'Night Audit',
        'Anti-Terrorism and Bomb Scare',
        'Dangerous Goods and Hijack',
        'Medical Services',
        'Accommodation and Hospitality',
        'Information Dissemination',
        'Specialized Handling of Passengers: WIPs, VIPs, Physically Challenged',
        'Evacuation on Land and Water',
      ],
    },
  ],
  gstm: [
    {
      title: 'Language & Communication',
      modules: [
        'Language Enhancement',
        'Accent Neutralization',
        'Introduction to Grammar',
        'Advanced Grammar',
        'Role-plays Extempore',
      ],
    },
    {
      title: 'Personality & Soft Skills',
      modules: ['Emotional Intelligence'],
    },
    {
      title: 'Grooming & Presentation',
      modules: [
        'The Grooming Process',
        'Skin Care',
        'Hair Care',
        'Art of Makeup',
        'Formal Look',
        'Casual Look',
        'Elegant Dressing',
        'Selection of Outfit',
      ],
    },
    {
      title: 'Aviation & Airport Operations',
      modules: [
        'History of Aviation',
        'Types of Aircraft',
        'Aircraft Exterior and Functions',
        'Theory of Flight',
        'Aviation Terminology & Abbreviation',
        'Map Reading Skills',
        'In-flight Announcements – English & Hindi',
        'Emergencies on Board',
        'Safety Equipment',
        'National Aviation Authorities & Role of State and Center',
        'Airport Access Control: BCAS/Security CISF & Others (Airline Security)',
        'Airport Security',
        'Airport Runway/Taxiway/Maintenance Tarmac/Ramp Area',
        'Airport Infrastructure: City side/Land side/Air side',
        'Airport Monitoring/Surveillance',
        'Airport Administration',
        'Airport Finance',
        'Airport Support System: Fire/Ambulance/Doctors/Water Reservoir',
        'Airport Cargo Security: Incoming/Outgoing Airport Cargo (DGR)',
        "Airport ULD's Equipments",
        'Ground Support Limits',
        'Airport Manager',
        'Airport Threats / Bird Hits / Incident / Accidents',
      ],
    },
    {
      title: 'Travel, Ticketing & Tourism',
      modules: [
        'Introduction to Galileo Reservation System & Features',
        'Types of Travels and Differences among all',
        'International Ticket & Routing',
        'International Itinerary Building',
        'Fares & Ticketing',
        'Passenger Handling',
        'Time Zones',
        'Domestic Ticket & Routing',
        'Basics of Passport & Visa',
        'Domestic Itinerary Building',
        'Encoding & Decoding Cities and Countries',
      ],
    },
  ],
  htcs: [
    {
      title: 'Language & Communication',
      modules: [
        'Language Enhancement',
        'Accent Neutralization',
        'Introduction to Grammar',
        'Advanced Grammar',
        'Role-plays Extempore',
      ],
    },
    {
      title: 'Personality & Soft Skills',
      modules: ['Emotional Intelligence'],
    },
    {
      title: 'Grooming & Presentation',
      modules: [
        'The Grooming Process',
        'Skin Care',
        'Hair Care',
        'Art of Makeup',
        'Formal Look',
        'Casual Look',
        'Elegant Dressing',
      ],
    },
    {
      title: 'Travel, Ticketing & Tourism',
      modules: [
        'Types of Travel & Difference Between Them',
        'Time Zones',
        'Domestic Ticketing and Routings',
        'International Ticketing and Routings',
        'Basic Knowledge of Passport & Visa Structures for Selected Countries',
        'Itinerary Building Techniques',
        'International Itineraries',
        'Domestic Itineraries',
        'Airport Monitoring/Surveillance',
      ],
    },
    {
      title: 'Hospitality & Hotel Operations',
      modules: [
        'Introduction to the Hospitality Industry',
        'Front Office Introduction',
        'Classification of Hotels',
        'Reservation',
        'Tax Structure',
        'Group Arrivals and Departures',
        'Overbooking',
        'Night Audit',
        'Types of Management',
        'Front Office Procedures for Emergency',
      ],
    },
  ],
  'interior-designing': [
    {
      title: 'Career Specialisations',
      modules: [
        'Interior Designer',
        'Furniture Designer',
        'Exhibition Designer',
        'Project Consultant',
        'Display Artist',
        'Design Consultant',
        'Faculty',
        'Commercial Complex Designer',
        'Home Furnishing Designer',
        'Tourist Resort Designer',
      ],
    },
  ],
  'fashion-designing': [
    {
      title: 'Design & Construction',
      modules: [
        'Sketching & Illustration',
        'Pattern Construction and Drafting Methods',
        'Garment Construction',
        'Grading',
        'Pattern Designing',
        'Fashion Model Drawing',
      ],
    },
    {
      title: 'Industry & Management',
      modules: [
        'Production Planning and Control',
        'Design Management & Fashion Coordination',
        'Textile Know How',
        'History of Garment Industries',
        'Case Studies, Design Collection',
      ],
    },
  ],
}

export function getModuleGroupsForCourse(courseId: string): ModuleGroup[] {
  return courseModuleGroups[courseId] ?? []
}
